[package]
name = "random_yg_card"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
rand = "0.8"
csv = "1.1"
actix-web = "4.0" 
serde = { version = "1", features = ["derive"] }
serde_json = "1"